import { FixtureDefinition, FixtureType } from '../types';

export const FIXTURE_DEFINITIONS: Record<FixtureType, FixtureDefinition> = {
  par: {
    type: 'par',
    name: 'PAR Can',
    description: 'Classic wash light with wide beam coverage',
    beamAngle: 50,
    canMove: false,
    isStrobe: false,
    isLaser: false,
    defaultColor: { r: 255, g: 100, b: 0 },
    icon: '💡',
    accentColor: '#ff6400',
  },
  'moving-head-spot': {
    type: 'moving-head-spot',
    name: 'Moving Spot',
    description: 'Narrow programmable beam — the star of any show',
    beamAngle: 12,
    canMove: true,
    isStrobe: false,
    isLaser: false,
    defaultColor: { r: 255, g: 255, b: 255 },
    icon: '🔦',
    accentColor: '#ffffff',
  },
  'moving-head-wash': {
    type: 'moving-head-wash',
    name: 'Moving Wash',
    description: 'Soft wide beam that can pan and tilt',
    beamAngle: 38,
    canMove: true,
    isStrobe: false,
    isLaser: false,
    defaultColor: { r: 0, g: 100, b: 255 },
    icon: '🌊',
    accentColor: '#0064ff',
  },
  'led-bar': {
    type: 'led-bar',
    name: 'LED Bar',
    description: 'Linear fixture with multiple color zones',
    beamAngle: 110,
    canMove: false,
    isStrobe: false,
    isLaser: false,
    defaultColor: { r: 0, g: 255, b: 100 },
    icon: '🌈',
    accentColor: '#00ff64',
  },
  strobe: {
    type: 'strobe',
    name: 'Strobe',
    description: 'High-intensity pulsing white light',
    beamAngle: 70,
    canMove: false,
    isStrobe: true,
    isLaser: false,
    defaultColor: { r: 255, g: 255, b: 255 },
    icon: '⚡',
    accentColor: '#ffffff',
  },
  laser: {
    type: 'laser',
    name: 'Laser',
    description: 'Razor-thin beam with dramatic reach',
    beamAngle: 1,
    canMove: true,
    isStrobe: false,
    isLaser: true,
    defaultColor: { r: 0, g: 255, b: 0 },
    icon: '🔴',
    accentColor: '#00ff00',
  },
};

export const PRESET_COLORS: { label: string; color: { r: number; g: number; b: number } }[] = [
  { label: 'White', color: { r: 255, g: 255, b: 255 } },
  { label: 'Red', color: { r: 255, g: 0, b: 0 } },
  { label: 'Orange', color: { r: 255, g: 100, b: 0 } },
  { label: 'Yellow', color: { r: 255, g: 220, b: 0 } },
  { label: 'Green', color: { r: 0, g: 255, b: 50 } },
  { label: 'Cyan', color: { r: 0, g: 220, b: 255 } },
  { label: 'Blue', color: { r: 0, g: 80, b: 255 } },
  { label: 'Purple', color: { r: 160, g: 0, b: 255 } },
  { label: 'Pink', color: { r: 255, g: 0, b: 200 } },
  { label: 'Amber', color: { r: 255, g: 160, b: 0 } },
  { label: 'UV', color: { r: 80, g: 0, b: 255 } },
  { label: 'Teal', color: { r: 0, g: 200, b: 180 } },
];

export const BEAT_COLOR_CYCLE = [
  { r: 255, g: 0, b: 0 },
  { r: 255, g: 100, b: 0 },
  { r: 255, g: 220, b: 0 },
  { r: 0, g: 255, b: 50 },
  { r: 0, g: 220, b: 255 },
  { r: 0, g: 80, b: 255 },
  { r: 160, g: 0, b: 255 },
  { r: 255, g: 0, b: 200 },
];
