import { VenueConfig, VenueId } from '../types';

export const VENUE_CONFIGS: Record<VenueId, VenueConfig> = {
  club: {
    id: 'club',
    name: 'Nightclub',
    description: 'Intimate dark space with front truss and booth lighting',
    emoji: '🎉',
    trusses: [
      { yPercent: 0.08, xStartPercent: 0.05, xEndPercent: 0.95, label: 'Front Truss' },
      { yPercent: 0.2, xStartPercent: 0.2, xEndPercent: 0.8, label: 'Mid Truss' },
    ],
    floorYPercent: 0.78,
    backWallYPercent: 0.55,
    ambientColor: '#0a0010',
    floorColor: '#111118',
    wallColor: '#0d0d1a',
    maxFixtures: 20,
  },
  concert: {
    id: 'concert',
    name: 'Concert Hall',
    description: 'Large professional stage with full rig',
    emoji: '🎸',
    trusses: [
      { yPercent: 0.06, xStartPercent: 0.02, xEndPercent: 0.98, label: 'FOH Truss' },
      { yPercent: 0.15, xStartPercent: 0.08, xEndPercent: 0.92, label: 'Mid Truss' },
      { yPercent: 0.26, xStartPercent: 0.15, xEndPercent: 0.85, label: 'Rear Truss' },
    ],
    floorYPercent: 0.82,
    backWallYPercent: 0.5,
    ambientColor: '#050510',
    floorColor: '#0d0d14',
    wallColor: '#080812',
    maxFixtures: 40,
  },
  theater: {
    id: 'theater',
    name: 'Theater',
    description: 'Classic proscenium stage with fly system',
    emoji: '🎭',
    trusses: [
      { yPercent: 0.07, xStartPercent: 0.05, xEndPercent: 0.95, label: 'Electric 1' },
      { yPercent: 0.18, xStartPercent: 0.1, xEndPercent: 0.9, label: 'Electric 2' },
      { yPercent: 0.3, xStartPercent: 0.15, xEndPercent: 0.85, label: 'Electric 3' },
    ],
    floorYPercent: 0.8,
    backWallYPercent: 0.52,
    ambientColor: '#0a0800',
    floorColor: '#12100a',
    wallColor: '#14100a',
    maxFixtures: 35,
  },
  bar: {
    id: 'bar',
    name: 'Bar / Lounge',
    description: 'Small intimate venue with minimal rigging',
    emoji: '🍺',
    trusses: [
      { yPercent: 0.1, xStartPercent: 0.1, xEndPercent: 0.9, label: 'Bar Truss' },
    ],
    floorYPercent: 0.76,
    backWallYPercent: 0.58,
    ambientColor: '#100800',
    floorColor: '#1a1208',
    wallColor: '#180e06',
    maxFixtures: 12,
  },
  festival: {
    id: 'festival',
    name: 'Festival Stage',
    description: 'Massive outdoor stage with towers and overhead rig',
    emoji: '🎪',
    trusses: [
      { yPercent: 0.04, xStartPercent: 0.0, xEndPercent: 1.0, label: 'Roof Truss' },
      { yPercent: 0.12, xStartPercent: 0.05, xEndPercent: 0.95, label: 'Mid Truss 1' },
      { yPercent: 0.22, xStartPercent: 0.1, xEndPercent: 0.9, label: 'Mid Truss 2' },
    ],
    floorYPercent: 0.84,
    backWallYPercent: 0.48,
    ambientColor: '#000a14',
    floorColor: '#08100a',
    wallColor: '#06080c',
    maxFixtures: 50,
  },
  church: {
    id: 'church',
    name: 'Church',
    description: 'Worship space with high ceilings and warm tones',
    emoji: '⛪',
    trusses: [
      { yPercent: 0.05, xStartPercent: 0.1, xEndPercent: 0.9, label: 'High Truss' },
      { yPercent: 0.22, xStartPercent: 0.15, xEndPercent: 0.85, label: 'Low Truss' },
    ],
    floorYPercent: 0.8,
    backWallYPercent: 0.5,
    ambientColor: '#08060a',
    floorColor: '#10100c',
    wallColor: '#120e08',
    maxFixtures: 25,
  },
};

export const VENUE_LIST: VenueId[] = ['club', 'concert', 'theater', 'bar', 'festival', 'church'];
